### ISSUE TITLE
Existing global KV-store collection prevents collection in app context from being opened.

### ISSUE THREAD

**Issue by jthunnissen** [LukeMurphey/lookup-editor#40] opened 2019-03-14 10:09 UTC
I observe the following issue:

Given 2 collections with the same name "collection1", one globally visible from app "A", the other in app visible in app "B".
Then:
* Opening the local app-visible collection1 in app B, shows collection1 from app A instead.
* Only after unsharing collection1 in A, collection1 from app B can be opened.

**Comment by LukeMurphey** [comment] 2019-03-14 22:51
I have seen this too. I remember investigating this and finding the problem was in Splunk's underlying endpoints which confuses the collections. I'll check again though.

**Comment by LukeMurphey** [comment] 2019-03-14 22:52
I did report this to Splunk on February of 2016 (SPL-114568).

The UI of the Lookup Editor tries to prevent users from making multiple lookups with the same name in order to avoid the problem. However, Splunk itself allows them and fails to distinguish between them.

**Comment by jthunnissen** [comment] 2019-05-02 09:35
Thank you for the clear reply. Could you provide me with a link to SPL-114568? I cannot find it in the docs.

**Comment by LukeMurphey** [comment] 2019-05-02 17:24
Unfortunately, the ticket is in a system that is not public.

I did check it and it is still open. I put in a comment trying to get more attention on it.

**Comment by jthunnissen** [comment] 2019-05-08 08:44
Thank you

**Comment by LukeMurphey** [comment] 2019-12-09 18:28
I tried to reproduce this on Splunk 8.0.0. It seems like this got fixed at some point as I could not reproduce the issue. No one updated SPL-114568 so I had no way of knowing that this got fixed.

Closing this accordingly.

**Closed by LukeMurphey** 2019-12-09 18:28 UTC
