### ISSUE TITLE
Column field name f2 not working and exiting edit mode

### ISSUE THREAD

**Issue by jxztan** [LukeMurphey/lookup-editor#45] opened 2020-03-17 02:45 UTC
Am currently experiencing two bugs with the lookup editor. 

1. Selecting the field name and pressing F2 no longer allows you to edit the field name. This used to work on previous versions but now the the only way to edit the field is to right click -> edit.

2. When trying to edit the field name, occasionally it will go into edit mode and immediately quit edit mode without any user input.

**Comment by LukeMurphey** [comment] 2020-04-01 18:45
I noticed this too. The problem is a bug in the component I am using. It has been fixed in a lter version of the component but that component (handsontable) has changed the licensing terms and it isn't clear to me if I am allowed to use the new version (see https://github.com/handsontable/handsontable/blob/develop/handsontable-non-commercial-license.pdf). I'm not making money on the project (I'm technically losing money on it) but I don't know if that is enough to qualify for the use of the free license.

I had previously considered seeing if I could get a license but I suspect that it going to be expensive. They don't even list a price for the SaaS license I would need (https://handsontable.com/pricing); I'm guessing it is not cheap.

My current plan is to replace this component with another one. I evaluated a bunch of them and have one picked out to try. I have a branch created to test it out but I haven't yet tried it. I'm hoping to get this done for version 3.4 (https://lukemurphey.net/versions/348).

**Comment by simonsigre** [comment] 2020-04-01 22:50
Thanks @LukeMurphey we all really appreciate your efforts here and love the tool

**Comment by jxztan** [comment] 2020-04-01 23:16
Thanks for the response and your hard work @LukeMurphey !

**Comment by darrendchow** [comment] 2020-04-01 23:23
Thanks @LukeMurphey Should definitely setup a Patron page appreciate all your work.

**Comment by aliemirlioglu** [comment] 2020-04-01 23:36
Massive thanks for the app @LukeMurphey. It's in my essential app list for any Splunk installs and gets used frequently.

**Comment by amanuelw** [comment] 2020-04-01 23:42
Awesome work @LukeMurphey, thank you for your time and effort. The app is indeed an essential tool.

**Comment by linsmeyerh** [comment] 2020-04-01 23:48
Thanks @LukeMurphey  for your time and hard work on this app. It is categorised as an essential tool in Splunk by many.

**Comment by Edmund-Tran** [comment] 2020-04-02 00:36
Jumping on the bandwagon here. Thank you @LukeMurphey! You've definitely made the workflow for myself and my team a lot easier and simpler over the last couple of years with this app. I'm sure everyone appreciates the work and time you've put into this app.

**Comment by clogs13** [comment] 2020-04-02 02:55
One of the first apps to be installed in most installations.  Thanks @LukeMurphey

**Comment by LukeMurphey** [comment] 2020-04-02 18:19
Thank you all for your nice comments, I appreciate it. I setup a GoFundMe and Patreon a while ago but never really did anything with them. The links are here: gf.me/u/xuqj88 and https://www.patreon.com/LukeMurphey

I spent some time last night seeing if I could get jexcel integrated. Its partially working. My plan is try to get this in version 3.4. jexcel will let do things like filtering which I have been wanting to do for a while.

**Comment by LukeMurphey** [comment] 2020-04-10 17:20
FYI: I am still working on this. I have handsontable mostly replaced now. The details of the work is here: https://lukemurphey.net/issues/2620

**Comment by LukeMurphey** [comment] 2020-04-13 05:36
I replaced handsontable with jexcel. I want to do more testing on it since this is rather radical change. The user experience is largely the same, I'm just worried about bugs since large chunk of the frontend code was rewritten.

BTW: with this change, column name changes are done by right-clicking the header and selecting rename.

**Closed by LukeMurphey** 2020-04-13 05:36 UTC

**Comment by LukeMurphey** [comment] 2020-04-14 18:50
3.4 is now live: https://splunkbase.splunk.com/app/1724/
